2024-12-19 03:31:10,835 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-12-19 03:31:10,835 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Configure stats pid to 149949
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Loading settings from /home/wangc/.config/wandb/settings
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Loading settings from /home/wangc/now/pure/ALinAirway/wandb/settings
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_green_t.py', 'program_abspath': '/home/wangc/now/pure/ALinAirway/train_green_t.py', 'program': 'train_green_t.py'}
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:_log_setup():521] Logging user logs to /home/wangc/now/pure/ALinAirway/wandb/run-20241219_033110-mpc490pd/logs/debug.log
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:_log_setup():522] Logging internal logs to /home/wangc/now/pure/ALinAirway/wandb/run-20241219_033110-mpc490pd/logs/debug-internal.log
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:init():561] calling init triggers
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'max_epoch': 50, 'batch_size': 1}
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:init():611] starting backend
2024-12-19 03:31:10,836 INFO    MainThread:149949 [wandb_init.py:init():615] setting up manager
2024-12-19 03:31:10,845 INFO    MainThread:149949 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-19 03:31:10,847 INFO    MainThread:149949 [wandb_init.py:init():623] backend started and connected
2024-12-19 03:31:10,859 INFO    MainThread:149949 [wandb_init.py:init():715] updated telemetry
2024-12-19 03:31:10,965 INFO    MainThread:149949 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-12-19 03:31:12,362 ERROR   MainThread:149949 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-19 03:31:13,156 ERROR   MainThread:149949 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-19 03:31:14,160 WARNING MsgRouterThr:149949 [router.py:message_loop():77] message_loop has been closed
